### ISSUE TITLE
Module not found: Can't resolve 'rest/index' in '..\node_modules\rockset\src'

### ISSUE THREAD

**Issue by CodeLiftSleep** [rockset/rockset-node-client#1]
Having this issue running a react-create-app and trying to run rockset...I followed the instructions and created environment variables for the api key and api server, but it is saying it can't find rest/index in the node_module/rockset/src directory?  I see the file there in the right path, I am not sure how to fix this...appears related to typescript not having a module defined for it

In rockset.js I get a notice: 
"Could not find a declaration module for module "./rest/index".   blah/blah/rockset/src/rest/index.js has implicitly any type."

**Comment by scottwmorris** [comment]
this issue has been resolved as of the last major update
